name: Build and Release PAK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install repak
        run: cargo install --git https://github.com/trumank/repak

      - name: Build PAK
        run: |
          mkdir output
          repak pack /patch/tw/~Ru_Patch_P
          mv /patch/tw/~Ru_Patch_P.pak output/~Ru_Patch_P.pak

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: output/~Ru_Patch_P.pak
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
